#项目运行配置环境
spring:
  application:
    name: demo
  # 激活哪一个环境的配置文件
  profiles:
    #    active: prod
    active: dev
    include: druid,mybatis-plus,thymeleaf,redis,rabbitmq
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
server:
  # 设置ContextPath以便兼容tomcat访问url形式
#  servlet:
#    context-path: /mind_map
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true
      buffered: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
  # 开启ssl认证
#  ssl:
#    enabled: true
#    key-store: classpath:keyStore/keystore-prod.jks
#    key-store-password: 123456
#    key-store-type: PKCS12
