# 用于开发环境环境

server:
  # 修改tomcat的访问端口号位8888，默认为8080
  port: 8888
#  servlet:
#    context-path: /mind_map
#  ssl:
#    enabled: true
#    # ip地址127.0.0.1
#    key-store: classpath:keyStore/keystore-dev.jks
#    key-store-password: 123456
#    key-store-type: PKCS12

spring:
  thymeleaf:
    cache: false
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.195.128:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: quec1994
    password: quec1994

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志
logging:
  path: ${user.dir}\target\logs
  level:
    root: info
#  config: classpath:logback-spring.xml



