# 用于生产环境

server:
  # 修改tomcat的访问端口号位8888，默认为8080
  port: 8443
  #  context-path: /mind_map
#  ssl:
#    enabled: true
#    # ip地址192.168.20.1
#    key-store: classpath:keyStore/keystore-prod.jks
#    key-store-password: klmtklmt
#    key-store-type: PKCS12

spring:
  thymeleaf:
    cache: true
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: root

# 日志
logging:
  path: ${user.dir}\logs
  level:
    root: info
