# 开发环境个性化配置

server:
  # 修改tomcat的访问端口号位8888，默认为8080
  port: 8888

spring:
  thymeleaf:
    cache: false
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.195.128:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: quec1994
    password: quec1994
  rabbitmq:
    # 主机地址
    host: 192.168.195.128
    # 端口号
    port: 5672
    # 用户名
    username: guest
    # 密码
    password: guest
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.195.128
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志
logging:
  path: ${user.dir}\target\logs
  level:
    root: info
#  config: classpath:logback-spring.xml



