# 测试环境个性化配置

server:
  # 修改tomcat的访问端口号位8888，默认为8080
  port: 8888

spring:
  thymeleaf:
    cache: true
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.214:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: root

# 日志
logging:
  path: ${user.dir}
  level:
    root: debug
