# 开发环境个性化配置

server:
  # 修改tomcat的访问端口号位8888，默认为8080
  port: 8888

spring:
  thymeleaf:
    cache: false
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: myuser
    password: userpassword
  rabbitmq:
    # 主机地址
    host: 192.168.195.128
    # 端口号
    port: 5672
    # 用户名
    username: guest
    # 密码
    password: guest
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志
logging:
  level:
    root: debug
  file:
    path: ${user.dir}\target\logs
#  config: classpath:logback-spring.xml



